### PR TITLE
Load already existing nodes and connections

### PR DESCRIPTION
**Pull request by orenyodfat**

### CODE REVIEW

**Comment by orenyodfat** [comment]
(This should be get into an issue...but there is no issues tab for this repo.at least I do not see that)
Few requirements for the sim visualisation:
1. Visulaize p2p msgs between 2 nodes:
   -The related nodes could be blink (or color with different color) for few second.
   -The link between the related nodes could be a little thicker for few second.
When we will have that we could visualise PSS msgs all the way from source to destination (include all relaying/fwding nodes).

2. The name of the node should be visible on the node it self .
   - If there is no space for that…the node name can be display when “hoovering” the mouse on that.

3. Already connected nodes should be visible (including their links). 
See update files for this PR

**Comment by lmars** [comment]
@orenyodfat we recently updated the backend to send the current node and connection events when you connect to the stream with `current=true` in the URL query (see https://github.com/ethersphere/go-ethereum/pull/109), so is this change necessary?

**Comment by holisticode** [comment]
With the above comment by @lmars, to me it doesn't seem necessary

**Comment by orenyodfat** [comment]
agree.It is old one ..before integrating  ethersphere/go-ethereum#109.

**Pull request closed without merging**
